// Generated by gencpp from file morai_msgs/EventInfo.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_EVENTINFO_H
#define MORAI_MSGS_MESSAGE_EVENTINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <morai_msgs/Lamps.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct EventInfo_
{
  typedef EventInfo_<ContainerAllocator> Type;

  EventInfo_()
    : option(0)
    , ctrl_mode(0)
    , gear(0)
    , lamps()
    , set_pause(false)  {
    }
  EventInfo_(const ContainerAllocator& _alloc)
    : option(0)
    , ctrl_mode(0)
    , gear(0)
    , lamps(_alloc)
    , set_pause(false)  {
  (void)_alloc;
    }



   typedef int8_t _option_type;
  _option_type option;

   typedef int32_t _ctrl_mode_type;
  _ctrl_mode_type ctrl_mode;

   typedef int32_t _gear_type;
  _gear_type gear;

   typedef  ::morai_msgs::Lamps_<ContainerAllocator>  _lamps_type;
  _lamps_type lamps;

   typedef uint8_t _set_pause_type;
  _set_pause_type set_pause;





  typedef boost::shared_ptr< ::morai_msgs::EventInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::EventInfo_<ContainerAllocator> const> ConstPtr;

}; // struct EventInfo_

typedef ::morai_msgs::EventInfo_<std::allocator<void> > EventInfo;

typedef boost::shared_ptr< ::morai_msgs::EventInfo > EventInfoPtr;
typedef boost::shared_ptr< ::morai_msgs::EventInfo const> EventInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::EventInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::EventInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::EventInfo_<ContainerAllocator1> & lhs, const ::morai_msgs::EventInfo_<ContainerAllocator2> & rhs)
{
  return lhs.option == rhs.option &&
    lhs.ctrl_mode == rhs.ctrl_mode &&
    lhs.gear == rhs.gear &&
    lhs.lamps == rhs.lamps &&
    lhs.set_pause == rhs.set_pause;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::EventInfo_<ContainerAllocator1> & lhs, const ::morai_msgs::EventInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::EventInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::EventInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::EventInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::EventInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::EventInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::EventInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::EventInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3525edb8661dfd06b6e59bbcb7d475b5";
  }

  static const char* value(const ::morai_msgs::EventInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3525edb8661dfd06ULL;
  static const uint64_t static_value2 = 0xb6e59bbcb7d475b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::EventInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/EventInfo";
  }

  static const char* value(const ::morai_msgs::EventInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::EventInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 option\n"
"int32 ctrl_mode\n"
"int32 gear\n"
"Lamps lamps\n"
"bool set_pause\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/Lamps\n"
"Header header\n"
"\n"
"int8 turnSignal\n"
"int8 emergencySignal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::morai_msgs::EventInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::EventInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.option);
      stream.next(m.ctrl_mode);
      stream.next(m.gear);
      stream.next(m.lamps);
      stream.next(m.set_pause);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EventInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::EventInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::EventInfo_<ContainerAllocator>& v)
  {
    s << indent << "option: ";
    Printer<int8_t>::stream(s, indent + "  ", v.option);
    s << indent << "ctrl_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ctrl_mode);
    s << indent << "gear: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gear);
    s << indent << "lamps: ";
    s << std::endl;
    Printer< ::morai_msgs::Lamps_<ContainerAllocator> >::stream(s, indent + "  ", v.lamps);
    s << indent << "set_pause: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_pause);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_EVENTINFO_H
