// Generated by gencpp from file morai_msgs/MoraiSimProcSrv.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MORAISIMPROCSRV_H
#define MORAI_MSGS_MESSAGE_MORAISIMPROCSRV_H

#include <ros/service_traits.h>


#include <morai_msgs/MoraiSimProcSrvRequest.h>
#include <morai_msgs/MoraiSimProcSrvResponse.h>


namespace morai_msgs
{

struct MoraiSimProcSrv
{

typedef MoraiSimProcSrvRequest Request;
typedef MoraiSimProcSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoraiSimProcSrv
} // namespace morai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::morai_msgs::MoraiSimProcSrv > {
  static const char* value()
  {
    return "6d340598acf4b7d6e6f913c45512bf48";
  }

  static const char* value(const ::morai_msgs::MoraiSimProcSrv&) { return value(); }
};

template<>
struct DataType< ::morai_msgs::MoraiSimProcSrv > {
  static const char* value()
  {
    return "morai_msgs/MoraiSimProcSrv";
  }

  static const char* value(const ::morai_msgs::MoraiSimProcSrv&) { return value(); }
};


// service_traits::MD5Sum< ::morai_msgs::MoraiSimProcSrvRequest> should match
// service_traits::MD5Sum< ::morai_msgs::MoraiSimProcSrv >
template<>
struct MD5Sum< ::morai_msgs::MoraiSimProcSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::MoraiSimProcSrv >::value();
  }
  static const char* value(const ::morai_msgs::MoraiSimProcSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::MoraiSimProcSrvRequest> should match
// service_traits::DataType< ::morai_msgs::MoraiSimProcSrv >
template<>
struct DataType< ::morai_msgs::MoraiSimProcSrvRequest>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::MoraiSimProcSrv >::value();
  }
  static const char* value(const ::morai_msgs::MoraiSimProcSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::morai_msgs::MoraiSimProcSrvResponse> should match
// service_traits::MD5Sum< ::morai_msgs::MoraiSimProcSrv >
template<>
struct MD5Sum< ::morai_msgs::MoraiSimProcSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::MoraiSimProcSrv >::value();
  }
  static const char* value(const ::morai_msgs::MoraiSimProcSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::MoraiSimProcSrvResponse> should match
// service_traits::DataType< ::morai_msgs::MoraiSimProcSrv >
template<>
struct DataType< ::morai_msgs::MoraiSimProcSrvResponse>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::MoraiSimProcSrv >::value();
  }
  static const char* value(const ::morai_msgs::MoraiSimProcSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MORAISIMPROCSRV_H
