// Generated by gencpp from file morai_msgs/MoraiSimProcSrvRequest.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MORAISIMPROCSRVREQUEST_H
#define MORAI_MSGS_MESSAGE_MORAISIMPROCSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <morai_msgs/MoraiSimProcHandle.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct MoraiSimProcSrvRequest_
{
  typedef MoraiSimProcSrvRequest_<ContainerAllocator> Type;

  MoraiSimProcSrvRequest_()
    : request()  {
    }
  MoraiSimProcSrvRequest_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef  ::morai_msgs::MoraiSimProcHandle_<ContainerAllocator>  _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoraiSimProcSrvRequest_

typedef ::morai_msgs::MoraiSimProcSrvRequest_<std::allocator<void> > MoraiSimProcSrvRequest;

typedef boost::shared_ptr< ::morai_msgs::MoraiSimProcSrvRequest > MoraiSimProcSrvRequestPtr;
typedef boost::shared_ptr< ::morai_msgs::MoraiSimProcSrvRequest const> MoraiSimProcSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63aeb3f26afc04a3d784ec3b35914d16";
  }

  static const char* value(const ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63aeb3f26afc04a3ULL;
  static const uint64_t static_value2 = 0xd784ec3b35914d16ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/MoraiSimProcSrvRequest";
  }

  static const char* value(const ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MoraiSimProcHandle request\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/MoraiSimProcHandle\n"
"uint8 sim_process_status\n"
"\n"
"int16 replay_option\n"
"string rosbag_file_name\n"
"int16 replay_target_option\n"
"\n"
"int32 replay_speed\n"
"int32 start_time\n"
;
  }

  static const char* value(const ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoraiSimProcSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::MoraiSimProcSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    s << std::endl;
    Printer< ::morai_msgs::MoraiSimProcHandle_<ContainerAllocator> >::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MORAISIMPROCSRVREQUEST_H
