// Generated by gencpp from file morai_msgs/MoraiMapSpecSrvResponse.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MORAIMAPSPECSRVRESPONSE_H
#define MORAI_MSGS_MESSAGE_MORAIMAPSPECSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <morai_msgs/MapSpec.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct MoraiMapSpecSrvResponse_
{
  typedef MoraiMapSpecSrvResponse_<ContainerAllocator> Type;

  MoraiMapSpecSrvResponse_()
    : response()  {
    }
  MoraiMapSpecSrvResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef  ::morai_msgs::MapSpec_<ContainerAllocator>  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoraiMapSpecSrvResponse_

typedef ::morai_msgs::MoraiMapSpecSrvResponse_<std::allocator<void> > MoraiMapSpecSrvResponse;

typedef boost::shared_ptr< ::morai_msgs::MoraiMapSpecSrvResponse > MoraiMapSpecSrvResponsePtr;
typedef boost::shared_ptr< ::morai_msgs::MoraiMapSpecSrvResponse const> MoraiMapSpecSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ece60c7ec9cd22d0f3d7405c24531d1";
  }

  static const char* value(const ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ece60c7ec9cd22dULL;
  static const uint64_t static_value2 = 0x0f3d7405c24531d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/MoraiMapSpecSrvResponse";
  }

  static const char* value(const ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MapSpec response\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/MapSpec\n"
"int32 plane_coordinate_system\n"
"int32 utm_num\n"
"\n"
"geometry_msgs/Vector3 utm_offset\n"
"\n"
"string ellipse\n"
"float64 central_latitude\n"
"float64 central_meridian\n"
"float64 scale_factor\n"
"float64 false_easting\n"
"float64 false_northing\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoraiMapSpecSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::MoraiMapSpecSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    s << std::endl;
    Printer< ::morai_msgs::MapSpec_<ContainerAllocator> >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MORAIMAPSPECSRVRESPONSE_H
