// Generated by gencpp from file morai_msgs/MoraiVehicleSpecSrvRequest.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MORAIVEHICLESPECSRVREQUEST_H
#define MORAI_MSGS_MESSAGE_MORAIVEHICLESPECSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <morai_msgs/VehicleSpecIndex.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct MoraiVehicleSpecSrvRequest_
{
  typedef MoraiVehicleSpecSrvRequest_<ContainerAllocator> Type;

  MoraiVehicleSpecSrvRequest_()
    : request()  {
    }
  MoraiVehicleSpecSrvRequest_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef  ::morai_msgs::VehicleSpecIndex_<ContainerAllocator>  _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoraiVehicleSpecSrvRequest_

typedef ::morai_msgs::MoraiVehicleSpecSrvRequest_<std::allocator<void> > MoraiVehicleSpecSrvRequest;

typedef boost::shared_ptr< ::morai_msgs::MoraiVehicleSpecSrvRequest > MoraiVehicleSpecSrvRequestPtr;
typedef boost::shared_ptr< ::morai_msgs::MoraiVehicleSpecSrvRequest const> MoraiVehicleSpecSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f60eb9d45044f97584dc4dc33ff04f2";
  }

  static const char* value(const ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f60eb9d45044f97ULL;
  static const uint64_t static_value2 = 0x584dc4dc33ff04f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/MoraiVehicleSpecSrvRequest";
  }

  static const char* value(const ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "VehicleSpecIndex request\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/VehicleSpecIndex\n"
"int32 unique_id\n"
;
  }

  static const char* value(const ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoraiVehicleSpecSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::MoraiVehicleSpecSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    s << std::endl;
    Printer< ::morai_msgs::VehicleSpecIndex_<ContainerAllocator> >::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MORAIVEHICLESPECSRVREQUEST_H
