// Generated by gencpp from file morai_msgs/MoraiTLIndex.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MORAITLINDEX_H
#define MORAI_MSGS_MESSAGE_MORAITLINDEX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct MoraiTLIndex_
{
  typedef MoraiTLIndex_<ContainerAllocator> Type;

  MoraiTLIndex_()
    : idx()  {
    }
  MoraiTLIndex_(const ContainerAllocator& _alloc)
    : idx(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _idx_type;
  _idx_type idx;





  typedef boost::shared_ptr< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> const> ConstPtr;

}; // struct MoraiTLIndex_

typedef ::morai_msgs::MoraiTLIndex_<std::allocator<void> > MoraiTLIndex;

typedef boost::shared_ptr< ::morai_msgs::MoraiTLIndex > MoraiTLIndexPtr;
typedef boost::shared_ptr< ::morai_msgs::MoraiTLIndex const> MoraiTLIndexConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::MoraiTLIndex_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::MoraiTLIndex_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiTLIndex_<ContainerAllocator2> & rhs)
{
  return lhs.idx == rhs.idx;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::MoraiTLIndex_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiTLIndex_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71e0c15635f115962468861139afa95e";
  }

  static const char* value(const ::morai_msgs::MoraiTLIndex_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71e0c15635f11596ULL;
  static const uint64_t static_value2 = 0x2468861139afa95eULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/MoraiTLIndex";
  }

  static const char* value(const ::morai_msgs::MoraiTLIndex_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string idx\n"
;
  }

  static const char* value(const ::morai_msgs::MoraiTLIndex_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idx);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoraiTLIndex_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::MoraiTLIndex_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::MoraiTLIndex_<ContainerAllocator>& v)
  {
    s << indent << "idx: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.idx);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MORAITLINDEX_H
