// Generated by gencpp from file morai_msgs/MoraiTLInfo.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MORAITLINFO_H
#define MORAI_MSGS_MESSAGE_MORAITLINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct MoraiTLInfo_
{
  typedef MoraiTLInfo_<ContainerAllocator> Type;

  MoraiTLInfo_()
    : header()
    , idx()
    , status(0)  {
    }
  MoraiTLInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , idx(_alloc)
    , status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _idx_type;
  _idx_type idx;

   typedef int16_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MoraiTLInfo_

typedef ::morai_msgs::MoraiTLInfo_<std::allocator<void> > MoraiTLInfo;

typedef boost::shared_ptr< ::morai_msgs::MoraiTLInfo > MoraiTLInfoPtr;
typedef boost::shared_ptr< ::morai_msgs::MoraiTLInfo const> MoraiTLInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::MoraiTLInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::MoraiTLInfo_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiTLInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.idx == rhs.idx &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::MoraiTLInfo_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiTLInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd593c80e25e130dfe063cc055f61aaf";
  }

  static const char* value(const ::morai_msgs::MoraiTLInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd593c80e25e130dULL;
  static const uint64_t static_value2 = 0xfe063cc055f61aafULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/MoraiTLInfo";
  }

  static const char* value(const ::morai_msgs::MoraiTLInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string idx\n"
"int16 status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::morai_msgs::MoraiTLInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.idx);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoraiTLInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::MoraiTLInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::MoraiTLInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "idx: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.idx);
    s << indent << "status: ";
    Printer<int16_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MORAITLINFO_H
