// Generated by gencpp from file morai_msgs/MoraiEventCmdSrvResponse.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MORAIEVENTCMDSRVRESPONSE_H
#define MORAI_MSGS_MESSAGE_MORAIEVENTCMDSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <morai_msgs/EventInfo.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct MoraiEventCmdSrvResponse_
{
  typedef MoraiEventCmdSrvResponse_<ContainerAllocator> Type;

  MoraiEventCmdSrvResponse_()
    : response()  {
    }
  MoraiEventCmdSrvResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef  ::morai_msgs::EventInfo_<ContainerAllocator>  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoraiEventCmdSrvResponse_

typedef ::morai_msgs::MoraiEventCmdSrvResponse_<std::allocator<void> > MoraiEventCmdSrvResponse;

typedef boost::shared_ptr< ::morai_msgs::MoraiEventCmdSrvResponse > MoraiEventCmdSrvResponsePtr;
typedef boost::shared_ptr< ::morai_msgs::MoraiEventCmdSrvResponse const> MoraiEventCmdSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator1> & lhs, const ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a4655da94bd0672ed74ad74e28d078b";
  }

  static const char* value(const ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a4655da94bd0672ULL;
  static const uint64_t static_value2 = 0xed74ad74e28d078bULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/MoraiEventCmdSrvResponse";
  }

  static const char* value(const ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "EventInfo response\n"
"\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/EventInfo\n"
"int8 option\n"
"int32 ctrl_mode\n"
"int32 gear\n"
"Lamps lamps\n"
"bool set_pause\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/Lamps\n"
"Header header\n"
"\n"
"int8 turnSignal\n"
"int8 emergencySignal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoraiEventCmdSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::MoraiEventCmdSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    s << std::endl;
    Printer< ::morai_msgs::EventInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MORAIEVENTCMDSRVRESPONSE_H
