// Generated by gencpp from file morai_msgs/MoraiSyncModeCtrlCmdSrv.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_MORAISYNCMODECTRLCMDSRV_H
#define MORAI_MSGS_MESSAGE_MORAISYNCMODECTRLCMDSRV_H

#include <ros/service_traits.h>


#include <morai_msgs/MoraiSyncModeCtrlCmdSrvRequest.h>
#include <morai_msgs/MoraiSyncModeCtrlCmdSrvResponse.h>


namespace morai_msgs
{

struct MoraiSyncModeCtrlCmdSrv
{

typedef MoraiSyncModeCtrlCmdSrvRequest Request;
typedef MoraiSyncModeCtrlCmdSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoraiSyncModeCtrlCmdSrv
} // namespace morai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::morai_msgs::MoraiSyncModeCtrlCmdSrv > {
  static const char* value()
  {
    return "1a537319e4c18b20b4792b07c454053f";
  }

  static const char* value(const ::morai_msgs::MoraiSyncModeCtrlCmdSrv&) { return value(); }
};

template<>
struct DataType< ::morai_msgs::MoraiSyncModeCtrlCmdSrv > {
  static const char* value()
  {
    return "morai_msgs/MoraiSyncModeCtrlCmdSrv";
  }

  static const char* value(const ::morai_msgs::MoraiSyncModeCtrlCmdSrv&) { return value(); }
};


// service_traits::MD5Sum< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest> should match
// service_traits::MD5Sum< ::morai_msgs::MoraiSyncModeCtrlCmdSrv >
template<>
struct MD5Sum< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::MoraiSyncModeCtrlCmdSrv >::value();
  }
  static const char* value(const ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest> should match
// service_traits::DataType< ::morai_msgs::MoraiSyncModeCtrlCmdSrv >
template<>
struct DataType< ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::MoraiSyncModeCtrlCmdSrv >::value();
  }
  static const char* value(const ::morai_msgs::MoraiSyncModeCtrlCmdSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::morai_msgs::MoraiSyncModeCtrlCmdSrvResponse> should match
// service_traits::MD5Sum< ::morai_msgs::MoraiSyncModeCtrlCmdSrv >
template<>
struct MD5Sum< ::morai_msgs::MoraiSyncModeCtrlCmdSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::morai_msgs::MoraiSyncModeCtrlCmdSrv >::value();
  }
  static const char* value(const ::morai_msgs::MoraiSyncModeCtrlCmdSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::morai_msgs::MoraiSyncModeCtrlCmdSrvResponse> should match
// service_traits::DataType< ::morai_msgs::MoraiSyncModeCtrlCmdSrv >
template<>
struct DataType< ::morai_msgs::MoraiSyncModeCtrlCmdSrvResponse>
{
  static const char* value()
  {
    return DataType< ::morai_msgs::MoraiSyncModeCtrlCmdSrv >::value();
  }
  static const char* value(const ::morai_msgs::MoraiSyncModeCtrlCmdSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_MORAISYNCMODECTRLCMDSRV_H
