// Generated by gencpp from file morai_msgs/PREventSrvResponse.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_PREVENTSRVRESPONSE_H
#define MORAI_MSGS_MESSAGE_PREVENTSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <morai_msgs/PREvent.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct PREventSrvResponse_
{
  typedef PREventSrvResponse_<ContainerAllocator> Type;

  PREventSrvResponse_()
    : response()  {
    }
  PREventSrvResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef  ::morai_msgs::PREvent_<ContainerAllocator>  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PREventSrvResponse_

typedef ::morai_msgs::PREventSrvResponse_<std::allocator<void> > PREventSrvResponse;

typedef boost::shared_ptr< ::morai_msgs::PREventSrvResponse > PREventSrvResponsePtr;
typedef boost::shared_ptr< ::morai_msgs::PREventSrvResponse const> PREventSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::PREventSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::PREventSrvResponse_<ContainerAllocator1> & lhs, const ::morai_msgs::PREventSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::PREventSrvResponse_<ContainerAllocator1> & lhs, const ::morai_msgs::PREventSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab9ee7cacf0c9bbfd2d3187b7dd6f3fa";
  }

  static const char* value(const ::morai_msgs::PREventSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab9ee7cacf0c9bbfULL;
  static const uint64_t static_value2 = 0xd2d3187b7dd6f3faULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/PREventSrvResponse";
  }

  static const char* value(const ::morai_msgs::PREventSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PREvent response\n"
"\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/PREvent\n"
"bool mountVehicle\n"
;
  }

  static const char* value(const ::morai_msgs::PREventSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PREventSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::PREventSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::PREventSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    s << std::endl;
    Printer< ::morai_msgs::PREvent_<ContainerAllocator> >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_PREVENTSRVRESPONSE_H
