// Generated by gencpp from file morai_msgs/ReplayInfo.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_REPLAYINFO_H
#define MORAI_MSGS_MESSAGE_REPLAYINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <morai_msgs/ObjectStatus.h>
#include <morai_msgs/ObjectStatus.h>
#include <morai_msgs/ObjectStatus.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct ReplayInfo_
{
  typedef ReplayInfo_<ContainerAllocator> Type;

  ReplayInfo_()
    : header()
    , ego_acc(0.0)
    , ego_brake(0.0)
    , ego_steer(0.0)
    , orientation()
    , linear_acceleration()
    , angular_velocity()
    , num_of_npcs(0)
    , num_of_pedestrian(0)
    , num_of_obstacle(0)
    , npc_list()
    , pedestrian_list()
    , obstacle_list()  {
    }
  ReplayInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ego_acc(0.0)
    , ego_brake(0.0)
    , ego_steer(0.0)
    , orientation(_alloc)
    , linear_acceleration(_alloc)
    , angular_velocity(_alloc)
    , num_of_npcs(0)
    , num_of_pedestrian(0)
    , num_of_obstacle(0)
    , npc_list(_alloc)
    , pedestrian_list(_alloc)
    , obstacle_list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _ego_acc_type;
  _ego_acc_type ego_acc;

   typedef double _ego_brake_type;
  _ego_brake_type ego_brake;

   typedef double _ego_steer_type;
  _ego_steer_type ego_steer;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef int32_t _num_of_npcs_type;
  _num_of_npcs_type num_of_npcs;

   typedef int32_t _num_of_pedestrian_type;
  _num_of_pedestrian_type num_of_pedestrian;

   typedef int32_t _num_of_obstacle_type;
  _num_of_obstacle_type num_of_obstacle;

   typedef std::vector< ::morai_msgs::ObjectStatus_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::morai_msgs::ObjectStatus_<ContainerAllocator> >> _npc_list_type;
  _npc_list_type npc_list;

   typedef std::vector< ::morai_msgs::ObjectStatus_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::morai_msgs::ObjectStatus_<ContainerAllocator> >> _pedestrian_list_type;
  _pedestrian_list_type pedestrian_list;

   typedef std::vector< ::morai_msgs::ObjectStatus_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::morai_msgs::ObjectStatus_<ContainerAllocator> >> _obstacle_list_type;
  _obstacle_list_type obstacle_list;





  typedef boost::shared_ptr< ::morai_msgs::ReplayInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::ReplayInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ReplayInfo_

typedef ::morai_msgs::ReplayInfo_<std::allocator<void> > ReplayInfo;

typedef boost::shared_ptr< ::morai_msgs::ReplayInfo > ReplayInfoPtr;
typedef boost::shared_ptr< ::morai_msgs::ReplayInfo const> ReplayInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::ReplayInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::ReplayInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::ReplayInfo_<ContainerAllocator1> & lhs, const ::morai_msgs::ReplayInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ego_acc == rhs.ego_acc &&
    lhs.ego_brake == rhs.ego_brake &&
    lhs.ego_steer == rhs.ego_steer &&
    lhs.orientation == rhs.orientation &&
    lhs.linear_acceleration == rhs.linear_acceleration &&
    lhs.angular_velocity == rhs.angular_velocity &&
    lhs.num_of_npcs == rhs.num_of_npcs &&
    lhs.num_of_pedestrian == rhs.num_of_pedestrian &&
    lhs.num_of_obstacle == rhs.num_of_obstacle &&
    lhs.npc_list == rhs.npc_list &&
    lhs.pedestrian_list == rhs.pedestrian_list &&
    lhs.obstacle_list == rhs.obstacle_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::ReplayInfo_<ContainerAllocator1> & lhs, const ::morai_msgs::ReplayInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::ReplayInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::ReplayInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::ReplayInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79280912719be2d1374fda7d2d0d3d7e";
  }

  static const char* value(const ::morai_msgs::ReplayInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79280912719be2d1ULL;
  static const uint64_t static_value2 = 0x374fda7d2d0d3d7eULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/ReplayInfo";
  }

  static const char* value(const ::morai_msgs::ReplayInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 ego_acc\n"
"float64 ego_brake\n"
"float64 ego_steer\n"
"\n"
"geometry_msgs/Quaternion orientation\n"
"\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"\n"
"geometry_msgs/Vector3 angular_velocity\n"
"\n"
"int32 num_of_npcs\n"
"int32 num_of_pedestrian\n"
"int32 num_of_obstacle\n"
"\n"
"ObjectStatus[] npc_list \n"
"\n"
"ObjectStatus[] pedestrian_list\n"
"\n"
"ObjectStatus[] obstacle_list \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: morai_msgs/ObjectStatus\n"
"int32 unique_id\n"
"int32 type\n"
"string name\n"
"float64 heading\n"
"\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 acceleration\n"
"geometry_msgs/Vector3 size\n"
"geometry_msgs/Vector3 position\n"
;
  }

  static const char* value(const ::morai_msgs::ReplayInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ego_acc);
      stream.next(m.ego_brake);
      stream.next(m.ego_steer);
      stream.next(m.orientation);
      stream.next(m.linear_acceleration);
      stream.next(m.angular_velocity);
      stream.next(m.num_of_npcs);
      stream.next(m.num_of_pedestrian);
      stream.next(m.num_of_obstacle);
      stream.next(m.npc_list);
      stream.next(m.pedestrian_list);
      stream.next(m.obstacle_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReplayInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::ReplayInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::ReplayInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ego_acc: ";
    Printer<double>::stream(s, indent + "  ", v.ego_acc);
    s << indent << "ego_brake: ";
    Printer<double>::stream(s, indent + "  ", v.ego_brake);
    s << indent << "ego_steer: ";
    Printer<double>::stream(s, indent + "  ", v.ego_steer);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "linear_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "angular_velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "num_of_npcs: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_of_npcs);
    s << indent << "num_of_pedestrian: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_of_pedestrian);
    s << indent << "num_of_obstacle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_of_obstacle);
    s << indent << "npc_list[]" << std::endl;
    for (size_t i = 0; i < v.npc_list.size(); ++i)
    {
      s << indent << "  npc_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::morai_msgs::ObjectStatus_<ContainerAllocator> >::stream(s, indent + "    ", v.npc_list[i]);
    }
    s << indent << "pedestrian_list[]" << std::endl;
    for (size_t i = 0; i < v.pedestrian_list.size(); ++i)
    {
      s << indent << "  pedestrian_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::morai_msgs::ObjectStatus_<ContainerAllocator> >::stream(s, indent + "    ", v.pedestrian_list[i]);
    }
    s << indent << "obstacle_list[]" << std::endl;
    for (size_t i = 0; i < v.obstacle_list.size(); ++i)
    {
      s << indent << "  obstacle_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::morai_msgs::ObjectStatus_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacle_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_REPLAYINFO_H
