// Generated by gencpp from file morai_msgs/SyncModeScenarioLoad.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_SYNCMODESCENARIOLOAD_H
#define MORAI_MSGS_MESSAGE_SYNCMODESCENARIOLOAD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct SyncModeScenarioLoad_
{
  typedef SyncModeScenarioLoad_<ContainerAllocator> Type;

  SyncModeScenarioLoad_()
    : frame(0)
    , file_name()
    , load_network_connection_data(false)
    , delete_all(false)
    , load_ego_vehicle_data(false)
    , load_surrounding_vehicle_data(false)
    , load_pedestrian_data(false)
    , load_obstacle_data(false)
    , set_pause(false)  {
    }
  SyncModeScenarioLoad_(const ContainerAllocator& _alloc)
    : frame(0)
    , file_name(_alloc)
    , load_network_connection_data(false)
    , delete_all(false)
    , load_ego_vehicle_data(false)
    , load_surrounding_vehicle_data(false)
    , load_pedestrian_data(false)
    , load_obstacle_data(false)
    , set_pause(false)  {
  (void)_alloc;
    }



   typedef uint64_t _frame_type;
  _frame_type frame;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _file_name_type;
  _file_name_type file_name;

   typedef uint8_t _load_network_connection_data_type;
  _load_network_connection_data_type load_network_connection_data;

   typedef uint8_t _delete_all_type;
  _delete_all_type delete_all;

   typedef uint8_t _load_ego_vehicle_data_type;
  _load_ego_vehicle_data_type load_ego_vehicle_data;

   typedef uint8_t _load_surrounding_vehicle_data_type;
  _load_surrounding_vehicle_data_type load_surrounding_vehicle_data;

   typedef uint8_t _load_pedestrian_data_type;
  _load_pedestrian_data_type load_pedestrian_data;

   typedef uint8_t _load_obstacle_data_type;
  _load_obstacle_data_type load_obstacle_data;

   typedef uint8_t _set_pause_type;
  _set_pause_type set_pause;





  typedef boost::shared_ptr< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> const> ConstPtr;

}; // struct SyncModeScenarioLoad_

typedef ::morai_msgs::SyncModeScenarioLoad_<std::allocator<void> > SyncModeScenarioLoad;

typedef boost::shared_ptr< ::morai_msgs::SyncModeScenarioLoad > SyncModeScenarioLoadPtr;
typedef boost::shared_ptr< ::morai_msgs::SyncModeScenarioLoad const> SyncModeScenarioLoadConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator1> & lhs, const ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator2> & rhs)
{
  return lhs.frame == rhs.frame &&
    lhs.file_name == rhs.file_name &&
    lhs.load_network_connection_data == rhs.load_network_connection_data &&
    lhs.delete_all == rhs.delete_all &&
    lhs.load_ego_vehicle_data == rhs.load_ego_vehicle_data &&
    lhs.load_surrounding_vehicle_data == rhs.load_surrounding_vehicle_data &&
    lhs.load_pedestrian_data == rhs.load_pedestrian_data &&
    lhs.load_obstacle_data == rhs.load_obstacle_data &&
    lhs.set_pause == rhs.set_pause;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator1> & lhs, const ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18d7884b2197b3f6a512fde8a7dedc57";
  }

  static const char* value(const ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18d7884b2197b3f6ULL;
  static const uint64_t static_value2 = 0xa512fde8a7dedc57ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/SyncModeScenarioLoad";
  }

  static const char* value(const ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 frame\n"
"\n"
"string file_name\n"
"bool load_network_connection_data\n"
"bool delete_all\n"
"bool load_ego_vehicle_data\n"
"bool load_surrounding_vehicle_data\n"
"bool load_pedestrian_data\n"
"bool load_obstacle_data\n"
"bool set_pause\n"
;
  }

  static const char* value(const ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
      stream.next(m.file_name);
      stream.next(m.load_network_connection_data);
      stream.next(m.delete_all);
      stream.next(m.load_ego_vehicle_data);
      stream.next(m.load_surrounding_vehicle_data);
      stream.next(m.load_pedestrian_data);
      stream.next(m.load_obstacle_data);
      stream.next(m.set_pause);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SyncModeScenarioLoad_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::SyncModeScenarioLoad_<ContainerAllocator>& v)
  {
    s << indent << "frame: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.frame);
    s << indent << "file_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.file_name);
    s << indent << "load_network_connection_data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.load_network_connection_data);
    s << indent << "delete_all: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.delete_all);
    s << indent << "load_ego_vehicle_data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.load_ego_vehicle_data);
    s << indent << "load_surrounding_vehicle_data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.load_surrounding_vehicle_data);
    s << indent << "load_pedestrian_data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.load_pedestrian_data);
    s << indent << "load_obstacle_data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.load_obstacle_data);
    s << indent << "set_pause: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_pause);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_SYNCMODESCENARIOLOAD_H
