// Generated by gencpp from file morai_msgs/VehicleCollisionData.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_VEHICLECOLLISIONDATA_H
#define MORAI_MSGS_MESSAGE_VEHICLECOLLISIONDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <morai_msgs/VehicleCollision.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct VehicleCollisionData_
{
  typedef VehicleCollisionData_<ContainerAllocator> Type;

  VehicleCollisionData_()
    : header()
    , collisions()  {
    }
  VehicleCollisionData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , collisions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::morai_msgs::VehicleCollision_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::morai_msgs::VehicleCollision_<ContainerAllocator> >> _collisions_type;
  _collisions_type collisions;





  typedef boost::shared_ptr< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleCollisionData_

typedef ::morai_msgs::VehicleCollisionData_<std::allocator<void> > VehicleCollisionData;

typedef boost::shared_ptr< ::morai_msgs::VehicleCollisionData > VehicleCollisionDataPtr;
typedef boost::shared_ptr< ::morai_msgs::VehicleCollisionData const> VehicleCollisionDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::VehicleCollisionData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::VehicleCollisionData_<ContainerAllocator1> & lhs, const ::morai_msgs::VehicleCollisionData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.collisions == rhs.collisions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::VehicleCollisionData_<ContainerAllocator1> & lhs, const ::morai_msgs::VehicleCollisionData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a928c1718fbb672e05004cbdd1dabd9";
  }

  static const char* value(const ::morai_msgs::VehicleCollisionData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a928c1718fbb672ULL;
  static const uint64_t static_value2 = 0xe05004cbdd1dabd9ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/VehicleCollisionData";
  }

  static const char* value(const ::morai_msgs::VehicleCollisionData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"VehicleCollision[] collisions\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/VehicleCollision\n"
"ObjectStatus[] crashed_vehicles\n"
"\n"
"================================================================================\n"
"MSG: morai_msgs/ObjectStatus\n"
"int32 unique_id\n"
"int32 type\n"
"string name\n"
"float64 heading\n"
"\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 acceleration\n"
"geometry_msgs/Vector3 size\n"
"geometry_msgs/Vector3 position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::morai_msgs::VehicleCollisionData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.collisions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleCollisionData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::VehicleCollisionData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::VehicleCollisionData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "collisions[]" << std::endl;
    for (size_t i = 0; i < v.collisions.size(); ++i)
    {
      s << indent << "  collisions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::morai_msgs::VehicleCollision_<ContainerAllocator> >::stream(s, indent + "    ", v.collisions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_VEHICLECOLLISIONDATA_H
