(cl:in-package morai_msgs-msg)
(cl:export '(UNIQUE_ID-VAL
          UNIQUE_ID
          TYPE-VAL
          TYPE
          NAME-VAL
          NAME
          HEADING-VAL
          HEADING
          VELOCITY-VAL
          VELOCITY
          ACCELERATION-VAL
          ACCELERATION
          SIZE-VAL
          SIZE
          POSITION-VAL
          POSITION
          ORIENTATION-VAL
          ORIENTATION
          TURN_SIGNAL-VAL
          TURN_SIGNAL
          GLOBAL_PATH_INFO-VAL
          GLOBAL_PATH_INFO
          LANE_DEPARTURE-VAL
          LANE_DEPARTURE
          DISTANCE_LEFT_LANE-VAL
          DISTANCE_LEFT_LANE
          DISTANCE_RIGHT_LANE-VAL
          DISTANCE_RIGHT_LANE
          OBJECT_YAW_RATE-VAL
          OBJECT_YAW_RATE
))