(cl:in-package morai_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          INTERSECTION_INDEX-VAL
          INTERSECTION_INDEX
          INTERSECTION_STATUS-VAL
          INTERSECTION_STATUS
          INTERSECTION_STATUS_TIME-VAL
          INTERSECTION_STATUS_TIME
))