(cl:in-package morai_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          UNIQUE_ID-VAL
          UNIQUE_ID
          ACCELERATION-VAL
          ACCELERATION
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          HEADING-VAL
          HEADING
          ACCEL-VAL
          ACCEL
          BRAKE-VAL
          BRAKE
          WHEEL_ANGLE-VAL
          WHEEL_ANGLE
          WHEEL_ANGLE_SPEED-VAL
          WHEEL_ANGLE_SPEED
          FL_WHEEL_SPEED-VAL
          FL_WHEEL_SPEED
          FR_WHEEL_SPEED-VAL
          FR_WHEEL_SPEED
          RL_WHEEL_SPEED-VAL
          RL_WHEEL_SPEED
          RR_WHEEL_SPEED-VAL
          RR_WHEEL_SPEED
          YAW_RATE-VAL
          YAW_RATE
))