# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/SyncModeCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SyncModeCmd(genpy.Message):
  _md5sum = "1cccc3e22a995ad33b1d0a9da180e8c1"
  _type = "morai_msgs/SyncModeCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string user_id
bool start_sync_mode
uint32 time_step
"""
  __slots__ = ['user_id','start_sync_mode','time_step']
  _slot_types = ['string','bool','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       user_id,start_sync_mode,time_step

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SyncModeCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.user_id is None:
        self.user_id = ''
      if self.start_sync_mode is None:
        self.start_sync_mode = False
      if self.time_step is None:
        self.time_step = 0
    else:
      self.user_id = ''
      self.start_sync_mode = False
      self.time_step = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.user_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.start_sync_mode, _x.time_step))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.user_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.user_id = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.start_sync_mode, _x.time_step,) = _get_struct_BI().unpack(str[start:end])
      self.start_sync_mode = bool(self.start_sync_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.user_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.start_sync_mode, _x.time_step))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.user_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.user_id = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.start_sync_mode, _x.time_step,) = _get_struct_BI().unpack(str[start:end])
      self.start_sync_mode = bool(self.start_sync_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BI = None
def _get_struct_BI():
    global _struct_BI
    if _struct_BI is None:
        _struct_BI = struct.Struct("<BI")
    return _struct_BI
